[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "roboreg"
version = "1.0.0"
authors = [
  { name="mhubii", email="m.huber_1994@hotmail.de" },
]
description = "Unified eye-in-hand / eye-to-hand calibration from RGB-D images using robot mesh as calibration target."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "faiss-gpu",
  "kinpy",
  "matplotlib",
  "numpy",
  "open3d",
  "opencv-python",
  "rich",
  "torch",
  "xacro",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: CC BY-NC 4.0 Deed",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/lbr-stack/roboreg"
Issues = "https://github.com/lbr-stack/roboreg/issues"

[project.scripts]
rr-dr = "roboreg.cli.rr_dr:main"
rr-hydra = "roboreg.cli.rr_hydra:main"
rr-render = "roboreg.cli.rr_render:main"
rr-segment = "roboreg.cli.rr_segment:main"
